name: Hello GitHub Actions

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: print hello
        run: echo "Hello from GitHub Actions Runner!" > hello.txt
